version: "3.9"

name: graffiti-spray-shop
services:
  server:
    build:
      context: ..
      dockerfile: docker/server.Dockerfile
    container_name: server
    ports:
      - "8000:5000"
    volumes:
      - ../server:/app
      - /app/node_modules
    environment:
      - PORT=5000

  client:
    build:
      context: ..
      dockerfile: docker/client.Dockerfile
    container_name: client
    ports:
      - "5173:5173"
    volumes:
      - ../client:/app
      - /app/node_modules
    environment:
      - VITE_API=http://localhost:8000

networks:
  default:
    name: spray_net